export const S = {
  // global
  app: {
    background: "#141414",
    minHeight: "100vh",
    fontFamily: "'Bebas Neue', 'Georgia', sans-serif",
    color: "white",
    overflowX: "hidden",
  },

  // landing
  landing: {
    minHeight: "100vh",
    background: "linear-gradient(rgba(0,0,0,0.55), rgba(0,0,0,0.55)), url(https://assets.nflxext.com/ffe/siteui/vlv3/f841d4c7-10e1-40af-bca1-07583908f1a5/4f0559f0-f9f6-4905-961f-13a88701833d/IN-en-20220502-popsignuptwoweeks-perspective_alpha_website_medium.jpg) center/cover no-repeat",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: "2rem",
  },
  landingLogo: {
    position: "absolute",
    top: "1.5rem",
    left: "4%",
    fontSize: "2.2rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "4px",
    color: "#e50914",
  },
  landingH1: {
    fontSize: "clamp(2rem, 5vw, 3.5rem)",
    fontWeight: "800",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "2px",
    marginBottom: "1rem",
  },
  landingH2: {
    fontSize: "clamp(1rem, 2.5vw, 1.5rem)",
    fontWeight: "400",
    marginBottom: "2rem",
    color: "#ddd",
    fontFamily: "Georgia, serif",
  },
  landingBtn: {
    background: "#e50914",
    color: "white",
    border: "none",
    padding: "1rem 2.5rem",
    fontSize: "1.2rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "2px",
    cursor: "pointer",
    borderRadius: "4px",
  },

  // navbar
  navbar: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem 4%",
    background: "linear-gradient(to bottom, rgba(0,0,0,0.9), transparent)",
  },
  navbarScrolled: {
    background: "#141414",
    borderBottom: "1px solid #333",
  },
  logo: {
    fontSize: "1.8rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "4px",
    color: "#e50914",
    cursor: "pointer",
  },
  navRight: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  searchInput: {
    background: "rgba(0,0,0,0.75)",
    border: "1px solid white",
    color: "white",
    padding: "0.4rem 0.8rem",
    borderRadius: "4px",
    fontSize: "0.9rem",
    fontFamily: "Georgia, serif",
    outline: "none",
    width: "200px",
  },
  navBtn: {
    background: "transparent",
    border: "none",
    color: "white",
    fontSize: "1.2rem",
    cursor: "pointer",
  },
  profileCircle: {
    width: "34px",
    height: "34px",
    borderRadius: "4px",
    background: "#e50914",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: "1rem",
    letterSpacing: "1px",
    cursor: "pointer",
  },

  // hero
  hero: {
    position: "relative",
    height: "85vh",
    overflow: "hidden",
  },
  heroImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center top",
  },
  heroOverlay: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(to right, rgba(0,0,0,0.85) 40%, transparent 100%), linear-gradient(to top, #141414 0%, transparent 60%)",
  },
  heroContent: {
    position: "absolute",
    bottom: "20%",
    left: "4%",
    maxWidth: "500px",
  },
  heroTag: {
    display: "inline-block",
    background: "#e50914",
    color: "white",
    padding: "0.2rem 0.8rem",
    fontSize: "0.75rem",
    fontFamily: "Georgia, serif",
    letterSpacing: "2px",
    marginBottom: "1rem",
    textTransform: "uppercase",
  },
  heroTitle: {
    fontSize: "clamp(2.5rem, 5vw, 4rem)",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "3px",
    marginBottom: "1rem",
    lineHeight: "1",
    textShadow: "2px 2px 8px rgba(0,0,0,0.5)",
  },
  heroDesc: {
    fontSize: "0.95rem",
    lineHeight: "1.6",
    color: "#ddd",
    marginBottom: "1.5rem",
    fontFamily: "Georgia, serif",
  },
  heroButtons: {
    display: "flex",
    gap: "1rem",
    flexWrap: "wrap",
  },
  btnPlay: {
    background: "white",
    color: "black",
    border: "none",
    padding: "0.7rem 1.8rem",
    fontSize: "1rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "2px",
    cursor: "pointer",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  btnInfo: {
    background: "rgba(109,109,110,0.7)",
    color: "white",
    border: "none",
    padding: "0.7rem 1.8rem",
    fontSize: "1rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "2px",
    cursor: "pointer",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },

  // rows
  rowsContainer: {
    paddingBottom: "4rem",
    marginTop: "-5rem",
    position: "relative",
    zIndex: 10,
  },
  row: {
    marginBottom: "2rem",
    padding: "0 4%",
  },
  rowTitle: {
    fontSize: "1.4rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "2px",
    marginBottom: "0.75rem",
    color: "#e5e5e5",
  },
  rowPosters: {
    display: "flex",
    gap: "6px",
    overflowX: "auto",
    paddingBottom: "0.5rem",
    scrollbarWidth: "none",
  },

  // movie card
  card: {
    flexShrink: 0,
    width: "180px",
    cursor: "pointer",
    borderRadius: "4px",
    overflow: "hidden",
    transition: "transform 0.2s ease",
    position: "relative",
  },
  cardImg: {
    width: "100%",
    height: "270px",
    objectFit: "cover",
    display: "block",
    borderRadius: "4px",
  },
  cardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    background: "linear-gradient(to top, rgba(0,0,0,0.95), transparent)",
    padding: "1rem 0.6rem 0.6rem",
    opacity: 0,
    transition: "opacity 0.2s ease",
  },
  cardTitle: {
    fontSize: "0.8rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "1px",
  },
  cardRating: {
    fontSize: "0.7rem",
    color: "#46d369",
    fontFamily: "Georgia, serif",
    marginTop: "2px",
  },

  // modal
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.8)",
    zIndex: 2000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "1rem",
  },
  modalBox: {
    background: "#181818",
    borderRadius: "8px",
    overflow: "hidden",
    width: "100%",
    maxWidth: "850px",
    maxHeight: "90vh",
    overflowY: "auto",
    position: "relative",
  },
  modalClose: {
    position: "absolute",
    top: "1rem",
    right: "1rem",
    background: "#181818",
    color: "white",
    border: "none",
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    fontSize: "1rem",
    cursor: "pointer",
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modalImgWrap: {
    position: "relative",
    height: "400px",
  },
  modalImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  modalGrad: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(to top, #181818 0%, transparent 60%)",
  },
  modalTitleArea: {
    position: "absolute",
    bottom: "2rem",
    left: "2rem",
  },
  modalTitle: {
    fontSize: "2.5rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "3px",
    marginBottom: "1rem",
  },
  modalBody: {
    padding: "1.5rem 2rem 2rem",
  },
  modalMeta: {
    display: "flex",
    gap: "1rem",
    alignItems: "center",
    marginBottom: "1rem",
    flexWrap: "wrap",
  },
  metaMatch: {
    color: "#46d369",
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: "1.1rem",
    letterSpacing: "1px",
  },
  metaYear: {
    color: "#ddd",
    fontFamily: "Georgia, serif",
    fontSize: "0.9rem",
  },
  metaHD: {
    border: "1px solid #808080",
    padding: "1px 6px",
    fontSize: "0.7rem",
    color: "#808080",
    fontFamily: "Georgia, serif",
  },
  modalDesc: {
    fontFamily: "Georgia, serif",
    lineHeight: "1.7",
    color: "#ddd",
    marginBottom: "1rem",
    fontSize: "0.95rem",
  },
  modalGenre: {
    fontFamily: "Georgia, serif",
    color: "#808080",
    fontSize: "0.85rem",
  },
  genreSpan: {
    color: "#ddd",
  },

  // footer
  footer: {
    padding: "3rem 4%",
    borderTop: "1px solid #333",
    color: "#808080",
    fontFamily: "Georgia, serif",
    fontSize: "0.8rem",
  },
  footerLogo: {
    fontSize: "1.4rem",
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: "3px",
    color: "#e50914",
    marginBottom: "1rem",
  },
};
